spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
        routes:
           # 按照优先顺序
          - id: product_route
            # 路由给mall-sales-product，lb代表负载均衡
            uri: lb://mall-sales-product
            predicates:
              - Path=/api/product/**
            filters:
              #从 网关端口/api/product/** 改为模块端口/product/**
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: third_party_service_route
            uri: lb://third-party-utils
            predicates:
              - Path=/api/thirdpartyservice/**
            filters:
              #从 网关端口/api/thirdpartyservice 改为模块端口/thirdpartyservice
              - RewritePath=/api/thirdpartyservice/(?<segment>/?.*),/$\{segment}

          - id: member_route
            uri: lb://mall-sales-member
            predicates:
              - Path=/api/member/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: houseware_route
            uri: lb://mall-sales-houseware
            predicates:
              - Path=/api/houseware/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: admin_route
            uri: lb://renren-fast
            predicates:
              - Path=/api/**
            filters:
              #从 网关端口/api/** 改为模块端口/api/renren-fast/**
              - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

          #网站主页的转发路径
          - id: nginx_mall_route
            uri: lb://mall-sales-product
            predicates:
              - Host=mall.com,item.mall.com

          #网站搜索页的转发路径
          - id: nginx_mall_search_route
            uri: lb://mall-search-service
            predicates:
              - Host=search.mall.com

          #认证服务的转发路径
          - id: nginx_mall_auth_route
            uri: lb://mall-auth-service
            predicates:
              - Host=auth.mall.com

          #购物车页面的转发路径
          - id: nginx_mall_shop_cart_route
            uri: lb://mall-sales-shop-cart
            predicates:
              - Host=cart.mall.com

          #订单页面的转发路径
          - id: mall_order_route
            uri: lb://mall-sales-order
            predicates:
              - Host=order.mall.com

          #商城会员页面的转发路径
          - id: mall_member_route
            uri: lb://mall-sales-member
            predicates:
              - Host=member.mall.com

          - id: coupon_route
            uri: lb://mall-sales-coupon
            predicates:
            - Path=/api/coupon/**
            filters:
             #网关路径重写，带/api的改为/
            - RewritePath=/api/(?<segment>.*),/$\{segment}

          #商品秒杀页面的转发路径
          - id: mall_seckill_route
            uri: lb://mall-sales-seckill
            predicates:
              - Host=seckill.mall.com
